[workspace]

[package]
name = "files"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
appkit = { package = "mochios-appkit", path = "../../tools/devkit/crates/appkit" }
mochios-workspace-protocol = { path = "../../user/crates/workspace-protocol" }
viewkit = { path = "../../libraries/viewkit" }

[target.'cfg(target_os = "mochios")'.dependencies]
libc = { git = "https://github.com/mochiOS/libc", package = "libc" }
mochi-user-platform = { path = "../../user/crates/platform", default-features = false, features = ["std"] }

[[bin]]
name = "files"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
